site_name: Tôi luyện Tiếng Nhật - Khu học mở
site_description: Mày tránh ra để t học Tiếng Nhật.
site_author: onlyduyy  
theme:
  name: material
  features:
    - navigation.sections
  palette:
    primary: indigo

nav:
  - 'Hướng dẫn':
    - 'Học': 'guide.md'
  - 'Công cụ & Cài đặt':
    - 'Yomitan': 'setup-yomichan.md'
    - 'Đào câu': 'sentence-mining.md'
  - 'Tài nguyên':
    - 'Tài nguyên': 'resources.md'
  - 'Nội dung tiêu thụ':
    - 'Youtube': 'youtube.md'
    - 'Podcast': 'podcasts.md'
    - 'Anime': 'anime.md'
    - 'LN & VN': 'novel.md'
    - 'Sách': 'sach.md'
    - 'Sách nói': 'audiobook.md'
      
theme:
  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      accent: grey
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: indigo
      accent: grey
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - navigation.instant
    - navigation.tabs
    - search.suggest
    - search.highlighting
    - search.share
  name: material

extra:
  generator: false