site_name: Tu luyện Tiếng Nhật
site_description: Tự học Tiếng Nhật thông qua Immersion và Comprehensible Input. Hoàn toàn miễn phí.
site_author: onlyduyy  
theme:
  name: material
  features:
    - navigation.sections
  palette:
    primary: indigo

nav:
  - Home: 'index.md'
  - 'Hướng dẫn':
    - 'Lộ trình học': 'guide.md'
    - 'Đầu vào dễ hiểu': 'input-guide.md'
  - 'FAQ':
    - 'Câu hỏi thường gặp': 'faq.md'
  - 'Học qua J-Media':
    - 'Anime': 'jp-anime.md'
    - 'Đọc': 'doc.md'
  - 'Công cụ & Cài đặt':
    - 'Yomichan': 'setup-yomichan.md'
    - 'Sentence Mining': 'sentence-mining.md'
  - 'Tổng hợp':
    - 'Tài nguyên': 'resources.md'
    - 'Cộng đồng': 'cong-dong.md'
  - 'Media':
    - 'Youtube': 'youtube.md'
    - 'Podcast': 'podcasts.md'
    - 'LN & VN': 'novel.md'
    - 'Phim & Drama': 'phim.md'
    - 'Sách': 'sach.md'
    - 'Audiobooks': 'audiobook.md'
      
theme:
  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      accent: grey
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: indigo
      accent: grey
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - navigation.instant
    - navigation.tabs
    - search.suggest
    - search.highlighting
    - search.share
  name: material

extra:
  generator: false