site_name: Tu luyện Tiếng Nhật
site_description: Tự học Tiếng Nhật thông qua Immersion và Comprehensible Input. Hoàn toàn miễn phí.
site_author: onlyduyy  
theme:
  name: material
  features:
    - navigation.sections
  palette:
    primary: indigo

nav:
  - Home: 'index.md'
  - 'Hướng dẫn':
    - 'JLPT': 'jlpt.md'
    - 'Comprehensible Input': 'input-guide.md'
    - 'Immersion': 'guide.md'
  - 'Khu linh tinh':
    - 'Anime': 'jp-anime.md'
    - 'Đọc': 'doc.md'
  - 'Công cụ':
    - 'Yomichan': 'setup-yomichan.md'
    - 'Sentence Mining': 'sentence-mining.md'
  - 'Tổng hợp':
    - 'Tài nguyên': 'resources.md'
    - 'Cộng đồng': 'cong-dong.md'
  - 'Nội dung':
    - 'Kho nội dung': 'media.md'
      
theme:
  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      accent: grey
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: indigo
      accent: grey
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - navigation.instant
    - navigation.tabs
    - search.suggest
    - search.highlighting
    - search.share
  name: material

extra:
  generator: false